"""Is this directory positively one of our handoff packages? Conservative by design.

A directory is ours only if it holds a manifest that parses, names the expected schema (a supported
version) and package type, and the directory contains exactly the files the manifest lists plus the
manifest, all plain files. Anything else (no manifest, malformed JSON, another application's
manifest, an unknown schema, extra files, links) is refused; nothing is ever deleted on a guess.

It must also be *intact*: every listed file has its recorded size and SHA-256. A package that was
edited by hand is refused (``HANDOFF_MODIFIED``) so ``--overwrite`` means "replace an intact package
previously generated by this tool", never "destroy the user's changes". Integrity is all that can be
checked here: the original score semantics are not in the package.
"""

import hashlib
import json
import os
import re
import stat
from pathlib import Path

from barbershop_tracks.core.handoff.errors import HandoffError
from barbershop_tracks.core.handoff.manifest import PACKAGE_TYPE, SCHEMA, SUPPORTED_VERSIONS
from barbershop_tracks.core.handoff.names import MANIFEST_NAME

_MAX_MANIFEST_BYTES = 1_000_000
_SCHEMA_VERSION = re.compile(r"^(.+)/([0-9]+)$")
_FILE_NAME = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$")
_SCHEMA_NAME = SCHEMA.rsplit("/", 1)[0]
_REPARSE_POINT = 0x400  # FILE_ATTRIBUTE_REPARSE_POINT (junctions, symlinks on Windows)


def is_link_or_reparse(path: Path) -> bool:
    """True for a symlink or a Windows reparse point (junction); such paths are never followed."""
    try:
        info = os.lstat(path)
    except OSError:
        return False
    if stat.S_ISLNK(info.st_mode):
        return True
    return bool(getattr(info, "st_file_attributes", 0) & _REPARSE_POINT)


def _refuse(directory: Path, why: str) -> HandoffError:
    return HandoffError(
        "HANDOFF_NOT_OURS",
        f"{directory.name} is not recognised as a barbershop-tracks handoff package ({why}); "
        "it was left untouched",
    )


def owned_files(directory: Path) -> tuple[str, ...]:
    """The file names of a recognised package (manifest included), or ``HANDOFF_NOT_OURS``."""
    if is_link_or_reparse(directory) or not directory.is_dir():
        raise _refuse(directory, "not a plain directory")
    manifest_path = directory / MANIFEST_NAME
    if is_link_or_reparse(manifest_path) or not manifest_path.is_file():
        raise _refuse(directory, f"no {MANIFEST_NAME}")
    try:
        if manifest_path.stat().st_size > _MAX_MANIFEST_BYTES:
            raise _refuse(directory, "manifest too large")
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as error:
        raise _refuse(directory, f"unreadable manifest: {error}") from error
    if not isinstance(manifest, dict):
        raise _refuse(directory, "manifest is not a JSON object")
    schema = manifest.get("schema")
    match = _SCHEMA_VERSION.match(schema) if isinstance(schema, str) else None
    if match is None or match.group(1) != _SCHEMA_NAME:
        raise _refuse(directory, "unexpected schema")
    if int(match.group(2)) not in SUPPORTED_VERSIONS:
        raise _refuse(directory, f"unsupported schema version {match.group(2)}")
    if manifest.get("package_type") != PACKAGE_TYPE:
        raise _refuse(directory, "unexpected package type")
    listed = manifest.get("files")
    if not isinstance(listed, list):
        raise _refuse(directory, "manifest lists no files")
    names: set[str] = {MANIFEST_NAME}
    recorded: dict[str, tuple[int, str]] = {}
    for entry in listed:
        name = entry.get("name") if isinstance(entry, dict) else None
        if not isinstance(name, str) or not _FILE_NAME.match(name) or name == MANIFEST_NAME:
            raise _refuse(directory, "manifest lists an invalid file name")
        size, digest = entry.get("bytes"), entry.get("sha256")
        if isinstance(size, bool) or not isinstance(size, int) or not isinstance(digest, str):
            raise _refuse(directory, f"manifest records no size or hash for {name}")
        names.add(name)
        recorded[name] = (size, digest)
    try:
        present = {child.name: child for child in directory.iterdir()}
    except OSError as error:
        raise _refuse(directory, f"cannot list the directory: {error}") from error
    if set(present) != names:
        raise _refuse(directory, "its contents differ from what the manifest lists")
    for child in present.values():
        if is_link_or_reparse(child) or not child.is_file():
            raise _refuse(directory, f"{child.name} is not a plain file")
    for name, (size, digest) in sorted(recorded.items()):
        try:
            data = present[name].read_bytes()
        except OSError as error:
            raise _refuse(directory, f"cannot read {name}: {error}") from error
        if len(data) != size or hashlib.sha256(data).hexdigest() != digest:
            raise HandoffError(
                "HANDOFF_MODIFIED",
                f"{name} in {directory.name} differs from what the manifest recorded, so the "
                "package was edited after it was generated; it was left untouched (move or delete "
                "it yourself to export afresh)",
            )
    return tuple(sorted(names))
